import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import {AuthProvider} from "@/app/Providers";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500', '700'] });

export const metadata = {
  title: "BookLine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="main  mx-auto p-4">
        <AuthProvider>
          <Toaster/>
          <Header />
          {children}
          <footer className="border-t p-8 text-center text-gray-500 mt-16">
            &copy; 2023 All rights reserved
          </footer>
          </AuthProvider>


        </main>
      </body>
    </html>
  );
}
